-- Vibely Chat + InsForge: run this in your InsForge project SQL / Postgres console.
-- Adjust if your platform uses a different auth schema than auth.users / auth.uid().

create table if not exists public.profiles (
    id uuid primary key references auth.users (id) on delete cascade,
    username text not null,
    email text,
    avatar_url text,
    created_at timestamptz not null default now()
);

create table if not exists public.conversations (
    id uuid primary key default gen_random_uuid(),
    participants uuid[] not null,
    created_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
    id bigint generated by default as identity primary key,
    sender_id uuid not null references public.profiles (id) on delete cascade,
    content text not null,
    conversation_id uuid references public.conversations (id) on delete cascade,
    created_at timestamptz not null default now()
);

create index if not exists idx_chat_messages_conversation_created
    on public.chat_messages (conversation_id, created_at asc);

alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.chat_messages enable row level security;

-- Authenticated users can read all profiles (for search). Tighten in production if needed.
drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated" on public.profiles
    for select to authenticated using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles
    for insert to authenticated with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
    for update to authenticated using (auth.uid() = id);

drop policy if exists "conversations_select_participant" on public.conversations;
create policy "conversations_select_participant" on public.conversations
    for select to authenticated using (auth.uid() = any (participants));

drop policy if exists "conversations_insert_participant" on public.conversations;
create policy "conversations_insert_participant" on public.conversations
    for insert to authenticated with check (auth.uid() = any (participants));

drop policy if exists "messages_select" on public.chat_messages;
create policy "messages_select" on public.chat_messages
    for select to authenticated using (
        conversation_id is null
        or exists (
            select 1 from public.conversations c
            where c.id = chat_messages.conversation_id
              and auth.uid() = any (c.participants)
        )
    );

drop policy if exists "messages_insert" on public.chat_messages;
create policy "messages_insert" on public.chat_messages
    for insert to authenticated with check (
        sender_id = auth.uid()
        and (
            conversation_id is null
            or exists (
                select 1 from public.conversations c
                where c.id = chat_messages.conversation_id
                  and auth.uid() = any (c.participants)
            )
        )
    );
